### ISSUE TITLE
UP求使用方法！[・_・?]

### ISSUE THREAD

**Issue by Weixiang** [AlexGuo1998/BadApple-LCD1602#1]
UP能不能发一下已经生成的BIN文件呢？
为了看个Bad Apple去下C编译器好麻烦……
( ･´ω`･ )

**Comment by AlexGuo1998** [comment]
做单片机开发，C编译器也是必备呀！

[https://github.com/AlexGuo1998/BadApple-LCD1602/releases/tag/v0.1.0](https://github.com/AlexGuo1998/BadApple-LCD1602/releases/tag/v0.1.0)
