### ISSUE TITLE
大佬，我的uno显示的都是乱码

### ISSUE THREAD

**Issue by VanKaikai** [AlexGuo1998/BadApple-LCD1602#2]
就是开始时能依稀看出在一堆11011111（字符表是这样讲的吧）和11101111中间有个SD后面就是一大堆的11011111了，这是什么情况。
还有，我是转接板接5v,gnd（没有电位器），然后别的引脚都直接连排母上的，应该没关系吧

**Comment by AlexGuo1998** [comment]
根据你的描述，不是很清楚你的情况……
建议先用Arduino自带的例程，检查一下屏幕能不能正常显示，然后用例程试试SD卡能不能读取。
